#!/bin/bash

if [ $# == 0 ]; then
    echo "No arguments"
elif [ $# == 1 ]; then
    find . | xargs grep $1
elif [ "$1" == "c" ]; then
    find . -name \*.h -print -o -name \*.c -print | xargs grep $2
elif [ "$1" == "cpp" ]; then
    find . -name \*.h -print -o -name \*.cpp -print | xargs grep $2
fi