#!/bin/bash

if [ -d $HOME/tmp_install ];
then
  echo "~/tmp_install already exists!"
  exit 1
fi

#Takes the file to install (to $HOME) and its path
function installfile {
if [ "$#" == 2 ]
then
  if [ -e "$1/$2" ]
  then
    #if { [ ! -e "$HOME/$2" ] || [ -L "$HOME/$2" ]; } && [ -e "$1/$2" ]
    if [ -L "$HOME/$2" ]
    then
      rm "$HOME/$2"
      ln -s "$1/$2" "$HOME/$2"
      echo "updated $2"
    else
      if [ ! -e "$HOME/$2" ]
      then
        ln -s "$1/$2" "$HOME/$2"
        echo "installed $2"
      else
        echo "Already exists: $HOME/$2"
      fi
    fi
  else
    echo "Source $1/$2 not found"
  fi
fi
}
# Takes the path relative to $SCRIPTPATH and the filename
function installfileinfolder {
if [ "$#" == 2 ]
then
    if [ ! -d "$HOME/$1" ] && [ -e "$SCRIPTPATH/$1" ]
    then
        mkdir -p "$1"
    fi
    installfile "$1" "$2"
fi
}
# Takes the path relative to $SCRIPTPATH
function installallinfolder {
if [ "$#" == 1 ]
then
    pth="$1/*"
    for i in $pth
    do
        if [ -f "$i" ]
        then
            file=$(basename "$i")
            dir=$(dirname "$i")
            installfileinfolder "$dir" "$file"
        fi
    done
fi

}

# Install dotfiles directly to $HOME
SCRIPTPATH=$( cd $(dirname $0) ; pwd -P )

echo "Installing config files from $SCRIPTPATH to $HOME"
shopt -s dotglob # List . files too
echo $SCRIPTPATH/files
DIRECTFILES=$(ls -A $SCRIPTPATH/files/direct)


for f in $DIRECTFILES
do
  installfile "$SCRIPTPATH/files/direct" "$f"
done

### Vim
# colors
if [ ! -d "$HOME/.vim/colors" ];
then
  mkdir -p "$HOME/.vim/colors"
fi
cp "$SCRIPTPATH/files/.vim/colors/BenokaiPrime.vim" "$HOME/.vim/colors"
# vundle
if [ ! -d "$HOME/.vim/bundle" ];
then
  mkdir -p "$HOME/.vim/bundle"
fi
git clone "http://github.com/VundleVim/Vundle.vim.git" "$HOME/.vim/bundle/Vundle.vim"
echo "If the git clone fails, either remove the line about ssh in the .gitconfig file, or generate a pub-key"
vim +PluginInstall +qall
# Vim-latex
mkdir tmp_install
git clone https://github.com/vim-latex/vim-latex tmp_install/vim-latex
cd tmp_install; make; cd ..
rm -rf tmp_install
echo "Vim stuff installed"

### ZSH
mv "$HOME/.zshrc" "$HOME/.bakzshrc"
# oh-my-zsh
if [ ! -f $HOME/.oh-my-zsh ];
then
  mkdir tmp_install
  git clone https://github.com/robbyrussell/oh-my-zsh.git tmp_install/
  echo "Remember to exit the zsh shell after installing"
  tmp_install/tools/install.sh
  rm -rf tmp_install
fi


# stub
cp "files/.zshrc-stub" "$HOME/.zshrc"
echo "Zsh installed"

chsh -s /bin/zsh

echo "-----------------------------------"
echo "Logout/login needed to change shell"
echo "-----------------------------------"

## Install scripts

if [ ! -d "$HOME/Dropbox" ]
then
  mkdir "$HOME/Documents/Scripts"
  installallinfolder "$HOME/Documents/Scripts"
  echo "Scripts installed"
fi
